version: '3.8'

services:
  racknerd-homepage:
    build: .
    image: jcubby86/racknerd-homepage:latest
    ports:
      - "5000:5000"
    environment:
      - RACKNERD_BASE_URL=https://nerdvm.racknerd.com
      - RACKNERD_KEY=<KEY>
      - RACKNERD_HASH=<HASH>
    restart: unless-stopped
